In [64]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import numpy as np

from sklearn.svm import SVC

## Impoetação dos dados

In [49]:
df = pd.read_csv('data.csv')
df = df.drop(['id', 'Unnamed: 32'], axis=1)
df.diagnosis = df.diagnosis.transform(lambda x: 0 if x == 'M' else 1)

## Normalização dos dados

In [50]:
col = df.columns
x = df.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled, columns=col)
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          0.0     0.521037      0.022658        0.545989   0.363733   
1          0.0     0.643144      0.272574        0.615783   0.501591   
2          0.0     0.601496      0.390260        0.595743   0.449417   
3          0.0     0.210090      0.360839        0.233501   0.102906   
4          0.0     0.629893      0.156578        0.630986   0.489290   
..         ...          ...           ...             ...        ...   
564        0.0     0.690000      0.428813        0.678668   0.566490   
565        0.0     0.622320      0.626987        0.604036   0.474019   
566        0.0     0.455251      0.621238        0.445788   0.303118   
567        0.0     0.644564      0.663510        0.665538   0.475716   
568        1.0     0.036869      0.501522        0.028540   0.015907   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.593753          0.792037        0.703140             0.731113   
1           0.289880          0.181768        0.203608             0.348757   
2           0.514309          0.431017        0.462512             0.635686   
3           0.811321          0.811361        0.565604             0.522863   
4           0.430351          0.347893        0.463918             0.518390   
..               ...               ...             ...                  ...   
564         0.526948          0.296055        0.571462             0.690358   
565         0.407782          0.257714        0.337395             0.486630   
566         0.288165          0.254340        0.216753             0.263519   
567         0.588336          0.790197        0.823336             0.755467   
568         0.000000          0.074351        0.000000             0.000000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.686364  ...      0.620776       0.141525         0.668310   
1         0.379798  ...      0.606901       0.303571         0.539818   
2         0.509596  ...      0.556386       0.360075         0.508442   
3         0.776263  ...      0.248310       0.385928         0.241347   
4         0.378283  ...      0.519744       0.123934         0.506948   
..             ...  ...           ...            ...              ...   
564       0.336364  ...      0.623266       0.383262         0.576174   
565       0.349495  ...      0.560655       0.699094         0.520892   
566       0.267677  ...      0.393099       0.589019         0.379949   
567       0.675253  ...      0.633582       0.730277         0.668310   
568       0.266162  ...      0.054287       0.489072         0.043578   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      0.450698          0.601136           0.619292         0.568610   
1      0.435214          0.347553           0.154563         0.192971   
2      0.374508          0.483590           0.385375         0.359744   
3      0.094008          0.915472           0.814012         0.548642   
4      0.341575          0.437364           0.172415         0.319489   
..          ...               ...                ...              ...   
564    0.452664          0.461137           0.178527         0.328035   
565    0.379915          0.300007           0.159997         0.256789   
566    0.230731          0.282177           0.273705         0.271805   
567    0.402035          0.619626           0.815758         0.749760   
568    0.020497          0.124084           0.036043         0.000000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.912027        0.598462                 0.418864  
1                0.639175        0.233590                 0.222878  
2                0.835052        0.403706                 0.213433  
3                0.884880        1.000000                 0.773711  
4                0.558419        0.157500                 0.142595  
..                    .

## Separação dos dados em treino e teste

In [67]:
# Separated the class variable 'y' and the others variables
y = df.diagnosis.values
X = df.drop(['diagnosis'], axis=1).values

# Separate test and training data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [66]:
X_test

array([[0.37905249, 0.52384173, 0.35761178, ..., 0.09962199, 0.        ,
        0.        ],
       [0.03540158, 0.53364897, 0.02895446, ..., 0.        , 0.29430317,
        0.29083038],
       [0.11756354, 0.38214406, 0.11277728, ..., 0.22395189, 0.25882121,
        0.24314574],
       ...,
       [0.37337309, 0.35508962, 0.36161979, ..., 0.34948454, 0.1584861 ,
        0.07182212],
       [0.2465332 , 0.12106865, 0.24386704, ..., 0.28134021, 0.37532032,
        0.24511347],
       [0.62989256, 0.15657761, 0.63098611, ..., 0.55841924, 0.15750049,
        0.14259478]])

In [72]:
X_test[0]

array([0.08258791, 0.20696652, 0.08326999, 0.03707317, 0.56305859,
       0.19210478, 0.0968135 , 0.09562624, 0.29747475, 0.55539174,
       0.01991671, 0.04999116, 0.02812986, 0.00404185, 0.22259238,
       0.14929252, 0.08229798, 0.19700701, 0.12942534, 0.10057626,
       0.06040555, 0.20255864, 0.07007321, 0.02438065, 0.66849369,
       0.20287957, 0.19616613, 0.36082474, 0.26828307, 0.30604749])

## Create SVM

In [83]:
clf = SVC(kernel='linear')
clf.fit(X_train, y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [91]:
pred = clf.predict(X_test)
c = 0
for i in range(len(pred)):
    if(y_test[i] == pred[i]):
        c+=1
        
print((c/len(pred)*100))

97.07602339181285


In [88]:
X_test[0]

array([0.08258791, 0.20696652, 0.08326999, 0.03707317, 0.56305859,
       0.19210478, 0.0968135 , 0.09562624, 0.29747475, 0.55539174,
       0.01991671, 0.04999116, 0.02812986, 0.00404185, 0.22259238,
       0.14929252, 0.08229798, 0.19700701, 0.12942534, 0.10057626,
       0.06040555, 0.20255864, 0.07007321, 0.02438065, 0.66849369,
       0.20287957, 0.19616613, 0.36082474, 0.26828307, 0.30604749])